### ISSUE TITLE
Forms API Incompatibilities

### ISSUE THREAD

**Issue by ebollens** [ucla/mwf#158]
In the initial draft of the Forms API Specification, the class for form styling was `form.form-full`. However, when we moved to lean CSS names for MWF 1.3, we elected to drop the `-full` qualifier. This would have meant that ideally the Forms API would have been invoked using `form.form`. Unfortunately, the implementation that made it into MWF 1.3 was for all `form` elements rather than `form.form`. While the class name might seem redundant in some cases, the problem is that without it, all forms get styled, regardless of context.

The best example of how this breaks things:

``` html
<form>
    <div class="menu">
        <ul>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
        </ul>
    </div>
<form>
```

It ends up pushing some strange padding into the menu definition itself because definitions from the Forms API leak into the DOM.

There are a few solutions that might jump to mind:
1. Require `.form` to use the Forms API.
2. Add a `.unstyled` class to the Forms API and make all definitions in the scope `form:not(.unstyled)` or equivalent.
3. Modify `.menu`, `.content`, etc. so that they beat out the definitions of the Forms API.

I would say that (1) is a non-starter because it will break apps already on MWF 1.3 using Forms API. This leaves us with two other options. Because Forms API doesn't screw with padding for basic phones, we might assume that `:not` is available, but I'm not convinced that this is the case for Windows Mobile and Blackberry devices classified as standard. This would mean that implementing (2) requires instead reversing the affects of the Forms API. Not sure I like this, as it requires content providers to make changes anyways. That leaves (3), which is tricky but might be achievable with techniques like negative margins.

Why does this matter? The predominate case I've seen this in (four production apps at UCLA) is .NET. It seems that it is a common practice to wrap the full page contents in a `form`. Experimentation will show whether or not this is reasonable either.

Some fix should be sought for the next MWF release to ensure that we aren't creating a barrier to upgrades for service providers that haven't moved to MWF 1.3 yet.

@ilin @loganfranken @Trott @edsakabu @rrocchio

**Comment by rrocchio** [comment]
Closing this issue as this system has long since been deprecated.
