### ISSUE TITLE
Archive this repository?

### ISSUE THREAD

**Issue by Trott** [ucla/mwf#175]
This repo hasn't been updated in over 6 years. AFAIK, no one is using this code in production anymore. Archiving it will send a clear message to anyone who comes across it that it is unmaintained and probably not what they are looking for. (To archive, go to Settings, scroll down to Danger Zone, take a moment to hum a little Kenny Loggins ditty, and then select Archive This Repository.)

**Comment by loganfranken** [comment]
Awww, end of an era: but, yeah, I agree this is a good idea!

**Comment by zkhalapyan** [comment]
End of en era. Goodbye MWF!
