### ISSUE TITLE
API for Single-Instance Common App with Branding Overrides

### ISSUE THREAD

**Issue by howardk** [ucla/mwf#79]
With mobile web apps using the framework are being done in a distributed fashion, it is desirable to be able to re-use an existing app (e.g., campus directory), but be able to override the branding (e.g., header, footer, CSS class to <body>) and link back label (e.g., Return to UCLA Mobile) and destination URL.  To prevent hijacking, there will need to some controls added (e.g., common domain, approved IP, etc.).

Adding this ability as part of the core MWF will give developers a common framework to provide this functionality instead of each app coming up with its own implementation.

FYI - this request is based on a conversation between Howard Kim, Ed Sakabu and Rose Rocchio at UCLA.

**Comment by rrocchio** [comment]
Closing this issue as this system has long since been deprecated.
